name: Comment on PR

on:
  workflow_run:
    workflows: ["PR Test Workflow"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download artifact from another workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: TestPR.yml   # Replace with the workflow file name that did the upload
          workflow_conclusion: success
          name: pr                                   # Must match artifact name used in the upload step
          path: ${{ github.workspace }}/pr           # Folder where contents will be extracted
          branch: main          

      - run: unzip pr.zip

      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const fs = require('fs');
            const issue_number = Number(fs.readFileSync('./NR'));
            const failed_tests = process.env.FAILED_TESTS || 'No failed tests.';
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `
                🚨 **RSpec Test Report:**
                
                ${failed_tests}
              `,
            });
